server:
  port: 7000
  servlet:
    context-path: /novel-subscription-fiction

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: novel-subscription-fiction
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/novel_subscription?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  instance:
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    secure-port-enabled: false
    secure-port: 443

    hostname: novel-subscription-fiction
    prefer-ip-address: true
    ip-address: 121.0.0.0
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://121.0.0.0:8005/eureka/,http://120.0.0.0:8004/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
