spring:
  application:
    name: novel-subscription-eureka
  profiles: server1
server:
  port: 8004
eureka:
  instance:
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    secure-port-enabled: false
    secure-port: 443

    hostname: server-light
    prefer-ip-address: true
    ip-address: 120.79.226.196
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://121.196.214.60:8003/eureka/

---
spring:
  application:
    name: novel-subscription-eureka
  profiles: server2
server:
  port: 8005
eureka:
  instance:
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    secure-port-enabled: false
    secure-port: 443

    hostname: server-cloud
    prefer-ip-address: true
    ip-address: 121.196.214.60
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://120.79.226.196:8002/eureka/