#spring:
#  application:
#    name: novel-subscription-eureka
#
#server:
#  port: 8004
#
#eureka:
#  instance:
#    non-secure-port-enabled: true
#    non-secure-port: ${server.port}
#    secure-port-enabled: false
#    secure-port: 443
#
#    hostname: server-light
#    prefer-ip-address: true
#    ip-address: 120.0.0.0
#    instance-id: ${eureka.instance.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://121.0.0.0:8005/eureka/
#
#---
spring:
  application:
    name: novel-subscription-eureka
server:
  port: 8005
eureka:
  instance:
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    secure-port-enabled: false
    secure-port: 443

    hostname: server-cloud
    prefer-ip-address: true
    ip-address: 121.0.0.0
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://120.0.0.0:8004/eureka/