server:
  port: 9000
spring:
  application:
    name: homepage-zuul
eureka:
  instance:
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    secure-port-enabled: false
    secure-port: 443

    hostname: homepage-zuul
    prefer-ip-address: true
    ip-address: 121
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://121:8003/eureka/,http://120:8002/eureka/
zuul:
  prefix: /imooc
  routes:
    course:
      path: /homepage-course/**
      serviceId: eureka-client-homepage-course
      strip-prefix: false
    user:
      path: /homepage-user/**
      serviceId: eureka-client-homepage-user
      strip-prefix: false
