server:
  port: 9000
spring:
  application:
    name: novel-subscription-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  prefix: /api
  routes:
    novel-subscription-fiction:
      path: /novel-subscription-fiction/**
      serviceId: novel-subscription-fiction
      strip-prefix: false
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
