server:
  port: 7001
  servlet:
    context-path: /novel-subscription-mail

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: novel-subscription-mail
  mail:
    host: smtp.163.com
    username:  # 用户名
    password:  # 授权密码
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
        imap:
          ssl:
            socketFactory:
              fallback: false
mail:
  fromMail:
    addr: # 发件邮箱

eureka:
  instance:
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    secure-port-enabled: false
    secure-port: 443

    hostname: novel-subscription-mail
    prefer-ip-address: true
    ip-address: 120.0.0.0
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://121.0.0.0:8005/eureka/,http://120.0.0.0:8004/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
