server:
  port: 7001
  servlet:
    context-path: /novel-subscription-mail

# 163邮箱
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: novel-subscription-mail
  mail:
    host: smtp.163.com
    username: 17770848782
    password: QWErty123
mail:
  fromMail:
    addr: 17770848782@163.com

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/